-- =====================   Szenario 1:

-- Aufgabe 2:

CREATE TABLE NotizSchlagwort(
	NotizOID int NOT NULL DEFAULT 'null',
	SchlagwortOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Web(
	URL varchar(200) DEFAULT 'null',
	WebOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE SchlagwortWeb(
	SchlagwortOID int NOT NULL DEFAULT 'null',
	WebOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE QuelleNotiz(
	QuelleOID int NOT NULL DEFAULT 'null',
	NotizOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Literatur(
	BuchName varchar(50) DEFAULT 'null',
	LiteraturOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Notiz(
	Inhalt varchar(200) DEFAULT 'null',
	NotizOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Quelle(
	Author null DEFAULT 'null',
	QuelleOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE SchlagwortLiteratur(
	SchlagwortOID int NOT NULL DEFAULT 'null',
	LiteraturOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Schlagwort(
	Wort varchar(50) DEFAULT 'null',
	SchlagwortOID int NOT NULL DEFAULT 'null'
);

ALTER TABLE NotizSchlagwort ADD CONSTRAINT PK_NotizSchlagwort PRIMARY KEY(NotizOID,SchlagwortOID);
ALTER TABLE Web ADD CONSTRAINT PK_Web PRIMARY KEY(WebOID);
ALTER TABLE SchlagwortWeb ADD CONSTRAINT PK_SchlagwortWeb PRIMARY KEY(SchlagwortOID,WebOID);
ALTER TABLE QuelleNotiz ADD CONSTRAINT PK_QuelleNotiz PRIMARY KEY(QuelleOID,NotizOID);
ALTER TABLE Literatur ADD CONSTRAINT PK_Literatur PRIMARY KEY(LiteraturOID);
ALTER TABLE Notiz ADD CONSTRAINT PK_Notiz PRIMARY KEY(NotizOID);
ALTER TABLE Notiz ADD CONSTRAINT PK_Notiz PRIMARY KEY(NotizOID);
ALTER TABLE Quelle ADD CONSTRAINT PK_Quelle PRIMARY KEY(QuelleOID);
ALTER TABLE Quelle ADD CONSTRAINT PK_Quelle PRIMARY KEY(QuelleOID);
ALTER TABLE SchlagwortLiteratur ADD CONSTRAINT PK_SchlagwortLiteratur PRIMARY KEY(SchlagwortOID,LiteraturOID);
ALTER TABLE Schlagwort ADD CONSTRAINT PK_Schlagwort PRIMARY KEY(SchlagwortOID);
ALTER TABLE Schlagwort ADD CONSTRAINT PK_Schlagwort PRIMARY KEY(SchlagwortOID);
ALTER TABLE Schlagwort ADD CONSTRAINT PK_Schlagwort PRIMARY KEY(SchlagwortOID);

ALTER TABLE NotizSchlagwort ADD CONSTRAINT FK_NotizSchlagwortNotiz FOREIGN KEY(NotizOID) REFERENCES Notiz(NotizOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE NotizSchlagwort ADD CONSTRAINT FK_NotizSchlagwortSchlagwort FOREIGN KEY(SchlagwortOID) REFERENCES Schlagwort(SchlagwortOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Web ADD CONSTRAINT FK_WebQuelle FOREIGN KEY(WebOID) REFERENCES Quelle(QuelleOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SchlagwortWeb ADD CONSTRAINT FK_SchlagwortWebSchlagwort FOREIGN KEY(SchlagwortOID) REFERENCES Schlagwort(SchlagwortOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SchlagwortWeb ADD CONSTRAINT FK_SchlagwortWebWeb FOREIGN KEY(WebOID) REFERENCES Web(WebOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE QuelleNotiz ADD CONSTRAINT FK_QuelleNotizQuelle FOREIGN KEY(QuelleOID) REFERENCES Quelle(QuelleOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE QuelleNotiz ADD CONSTRAINT FK_QuelleNotizNotiz FOREIGN KEY(NotizOID) REFERENCES Notiz(NotizOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Literatur ADD CONSTRAINT FK_LiteraturQuelle FOREIGN KEY(LiteraturOID) REFERENCES Quelle(QuelleOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SchlagwortLiteratur ADD CONSTRAINT FK_SchlagwortLiteraturSchlagwort FOREIGN KEY(SchlagwortOID) REFERENCES Schlagwort(SchlagwortOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE SchlagwortLiteratur ADD CONSTRAINT FK_SchlagwortLiteraturLiteratur FOREIGN KEY(LiteraturOID) REFERENCES Literatur(LiteraturOID) ON DELETE NO ACTION ON UPDATE NO ACTION;



-- ==============================   Szenario 2:

-- Aufgabe 2:

CREATE TABLE Mail(
	Inhalt varchar(200) DEFAULT 'null',
	MailOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE PersonNotiz(
	PersonOID int NOT NULL DEFAULT 'null',
	NotizOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Notiz(
	Text varchar(200) DEFAULT 'null',
	NotizOID int NOT NULL DEFAULT 'null'
);

CREATE TABLE Person(
	Vorname varchar(200) DEFAULT 'null',
	Nachname varchar(200) DEFAULT 'null',
	PersonOID int NOT NULL DEFAULT 'null'
);

ALTER TABLE PersonNotiz ADD CONSTRAINT PK_PersonNotiz PRIMARY KEY(PersonOID,NotizOID);
ALTER TABLE Notiz ADD CONSTRAINT PK_Notiz PRIMARY KEY(NotizOID);
ALTER TABLE Person ADD CONSTRAINT PK_Person PRIMARY KEY(PersonOID);

ALTER TABLE Mail ADD CONSTRAINT FK_MailPerson FOREIGN KEY(MailOID) REFERENCES Person(PersonOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Mail ADD CONSTRAINT FK_MailNotiz FOREIGN KEY(MailOID) REFERENCES Notiz(NotizOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE PersonNotiz ADD CONSTRAINT FK_PersonNotizPerson FOREIGN KEY(PersonOID) REFERENCES Person(PersonOID) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE PersonNotiz ADD CONSTRAINT FK_PersonNotizNotiz FOREIGN KEY(NotizOID) REFERENCES Notiz(NotizOID) ON DELETE NO ACTION ON UPDATE NO ACTION;






